import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:geminai/core/constants/app_colors.dart';
import 'package:get/get.dart';
import 'package:google_ml_kit/google_ml_kit.dart';
import 'package:image_cropper/image_cropper.dart';
import 'package:image_picker/image_picker.dart';
import 'package:speech_to_text/speech_to_text.dart';

import '../widgets/loading_dialog.dart';
import 'chat_controller.dart';

class HomeController extends GetxController {
  RxInt selectTabIndex = 0.obs;
  RxInt selectIndex = 0.obs;
  final sendChatController = TextEditingController().obs;
  final messageCtr = TextEditingController().obs;
  final commonQuestionCtr = TextEditingController().obs;
  RxBool speechEnabled = false.obs;
  RxBool isData = false.obs;
  RxString lastWords = ''.obs;
  final speechToText = SpeechToText().obs;
  final chatController = Get.put(ChatController());
  List historyList = [
    {"history": "Hi", "dec": "Hello!, how can assist you today?", "date": DateTime.now()},
    {
      "history": "Name the differences between a list and a tuple in Python. ...",
      "dec":
          "A programmer who applies for Junior Python developer jobs should have a solid understanding of Python’s syntax structures and the differences between them",
      "date": DateTime.now()
    },
    {"history": "Is Python case-sensitive?", "dec": "Yes, Python is a case-sensitive language. ", "date": DateTime.now()},
    {
      "history": "Define monkey-patching",
      "dec": "Python allows software developers to change the behavior of a module at runtime.",
      "date": DateTime.now()
    },
    {
      "history": "What is the use of the map function in Python?",
      "dec":
          "The map() function helps execute a function for all items in the iterated object (list, dictionary, set, or tuple). It has two arguments: ",
      "date": DateTime.now()
    },
  ];

  List suggestionList = [
    {
      "title": "Continue",
      "list": ["What is flutter ?", "How can make sandwich?"],
      "listDec": ["What is flutter listDec ?", "How can make sandwich?"],
      "color": AppColors.purpleColor
    },
    {
      "title": "Understand",
      "list": ["advancements in technology", "whole fact", "economic concepts", "are we there yet?"],
      "listDec": [
        "There have been a lot of advancements in autonomous vehicles over the past few years.How are people reacting to the fast-growing industry? What’s the potential impact to the economy, urban infrastructure, and the way we behave and interact with one another?",
        "I’m going whale watching this weekend and want to be an expert on killer whales, tell me a few unique facts about them.",
        "You’re an economics professor. Teach me the concept of game theory in simple terms.What are some real-world examples of how this would be applied? At the very end, include a glossary of concepts/vocabulary that I should know related to this subject.",
        "How long is the drive from Atlanta to Orlando and give me some ideas for how to keep 3 kids entertained in the car",
      ],
      "color": AppColors.primaryColor
    },
    {
      "title": "Create",
      "list": ["revise my writing ", "beginner’s guide to", "design a schema", "refund request mail", "language study plan", "seasonal recipe idea"],
      "listDec": [
        "Rewrite the text below to improve its writing quality, flow, readability and coherence. Make sure to fix any grammar and spelling mistakes.You are a professional editor, skilled at improving the clarity and concision of writing. You can rephrase sentences to make them more effective, and you can add details to make them more interesting. You can also correct any grammatical or spelling errors.",
        "Write a beginner’s guide to kite-surfing.You are an expert, skilled at providing the best information for people new to this activity. Provide a comprehensive overview of what is needed to get started. Be concise."
            "How to Design a Database Schema, With Examples",
        "How To Write A Refund Request Letter Step by Step Guide",
        "I want to learn a new language: Italian.You are a professional language tutor, skilled at creating personalized study plans for students of all levels. Create a study plan for me that will help me reach my goal of fluency. I have no knowledge of the language and would like to get to a conversational level in 3 months.Outline a week-by-week plan for how I can achieve my goal. Include weeks 1-12. Include a detailed curriculum.",
        "I want to make a salad that will be appropriate to serve at Thanksgiving dinner.You are an expert chef and food connoisseur, skilled at pairing flavors and textures.Be precise and specific in your ingredients and instructions. Ensure that the recipe is easy to follow and that the end result is delicious.",
      ],
      "color": AppColors.orangeColor
    },
    {
      "title": "Explore",
      "list": ["resume improvements", "best place visit near my place", "New language phrases", "delicious noodles", "date night planning"],
      "listDec": [
        "I’m writing a resume and need your help.Here’s what I want to say:\nsoftware engineer, tech lead\npython, java, C++\nled team of 10 people to build FizzBuzzPro (+50% revenue)\nTransform that into a list of power phrases.\n Write in a clear, concise style that is easy to read and understand.",
        "What are the best parks in location: Barcelona? You are a local guide, skilled at finding the most interesting and popular places in a city. Provide a detailed overview of the best parks in this city, including a brief description of each one and why it is worth visiting.",
        "New language phrases Dec",
        "What are some ways to make instant noodles even more delicious?",
        "Help me plan a date night. Find a nice sushi restaurant with availability this friday between 7 and 8pm. Suggest a dessert spot within walking distance of the restaurant."
      ],
      "color": AppColors.skyBlueColor
    },
  ];

  final personalFinance = [
    "How do I create a budget?",
    "What are the best ways to save money?",
    "How do I pay off debt?",
    "What are some common types of debt and how do I manage them?",
    "How do I improve my credit score?",
    "What are some common financial",
    "mistakes to avoid?",
    "How can I create a retirement savings plan?",
    "How do I invest in the stock market?",
    "What are some common investment strategies?",
    "How can I build an emergency fund?",
    "How do I calculate my net worth?",
    "What are the best ways to save for my children's education?",
    "How can I create a debt repayment plan?",
    "What are some common financial scams to avoid?",
    "How can I negotiate a lower interest rate on my credit card?",
    "How do I choose the right insurance policies?",
    "What are the best ways to save for a",
    "down payment on a house?",
    "How can I start investing with a small amount of money?",
    "How do I plan for taxes?",
    "What are the best ways to save for a vacation?",
    "How can I create a successful investment portfolio?",
    "What are some common retirement planning mistakes to avoid?",
    "How do I balance my short-term and long-term financial goals?",
    "How can I maximize my savings and minimize my expenses?",
    "What are the best ways to save money on groceries and household expenses?",
    "How do I negotiate a better salary or raise?",
    "How can I manage my finances during a recession or economic downturn?",
    "What are the best ways to save for a big purchase like a car or home?",
    "How can I create a passive income stream?",
    "What are the most important financial planning tools and resources?",
    "How can I create a financial plan for starting my own business?",
    "How do I create a successful investment strategy for my retirement?",
    "What are the best ways to pay off student loans?",
    "How can I manage my finances during a job loss or career transition?",
    "How can I create a successful investment plan for my children's future?",
    "What are the best ways to save for a child's wedding?",
    "How do I calculate and manage my debt- to-income ratio?",
    "How can I create a successful investment plan for my grandchildren's future?",
    "How can I save for a comfortable retirement while supporting my elderly parents?",
    "What are the best ways to save for a second home or vacation property?",
    "How can I maximize my retirement savings and minimize my taxes?",
    "What are the best ways to save for a child's college education while paying off debt?",
    "How do I choose the right financial advisor?",
    "How can I protect my assets and minimize my liability?",
    "What are the best ways to save for a sabbatical or career break?",
    "How can I create a successful investment plan for my legacy?",
    "How can I create a successful investment plan for my estate?",
    "How do I plan for my long-term care needs?",
    "How can I create a successful investment plan for my charitable giving?",
    "What are the best ways to manage my finances during a pandemic or other crisis?",
  ];
  final personalDevelopment = [
    "What is personal development and why is it important?",
    "How do I set goals for personal development?",
    "What are the best ways to track my personal development progress?",
    "How can I overcome procrastination?",
    "How can I improve my time management skills?",
    "How can I improve my focus and concentration?",
    "How can I improve my memory?",
    "How can I improve my critical thinking skills?",
    "How can I improve my decision- making skills?",
    "How can I improve my communication skills?",
    "How can I improve my public speaking skills?",
    "How can I improve my leadership skills?",
    "How can I improve my teamwork skills?",
    "How can I improve my emotional intelligence?",
    "How can I improve my self-confidence?",
    "How can I improve my self-esteem?",
    "How can I improve my resilience?",
    "How can I improve my adaptability?",
    "How can I improve my creativity?",
    "How can I improve my problem- solving skills?",
    "How can I improve my negotiation skills?",
    "How can I improve my networking skills?",
    "How can I improve my financial management skills?",
    "How can I improve my career development?",
    "How can I improve my work-life balance? >",
    "How can I improve my stress management skills?",
    "How can I improve my mindfulness practice?",
    "How can I improve my physical health?",
    "How can I improve my mental health?",
    "How can I improve my sleep habits?",
    "How can I improve my nutrition habits?",
    "How can I improve my exercise routine?",
    "How can I improve my hobbies and interests?",
    "How can I improve my social skills?",
    "How can I improve my cultural awareness?",
    "How can I improve my language skills?",
    "How can I improve my writing skills?",
    "How can I improve my reading skills?",
    "How can I improve my technological skills?",
    "How can I improve my environmental awareness?",
    "How can I improve my civic engagement?",
    "How can I improve my volunteering skills?",
    "How can I improve my spiritual practices?",
    "How can I improve my travel experiences?",
    "How can I improve my personal branding?",
    "How can I improve my online presence?",
    "How can I improve my overall happiness?",
    "How can I improve my sense of purpose?",
    "How can I improve my self-awareness?",
    "How can I maintain my personal development over time?",
  ];
  final timeManagementAndProductivity = [
    "How can I manage my time when preparing for a presentation?",
    "How can I manage my time when planning a large event?",
    "How can I manage my time when working on creative projects?",
    "How can I use mindfulness to improve my productivity?",
    "How can I manage my time when dealing with unexpected events?",
    "How can I manage my time when dealing with stress?",
    "How can I manage my time when dealing with multiple deadlines?",
    "How can I manage my time when dealing with a heavy workload?",
    "How can I manage my time when dealing with difficult colleagues or clients?",
    "How can I manage my time when dealing with a difficult boss?",
    "How can I manage my time when dealing with a difficult project?",
    "How can I manage my time when dealing with a difficult customer?",
    "How can I manage my time when dealing with a difficult team member?",
    "How can I manage my time when dealing with a difficult family situation?",
    "How can I manage my time when dealing with a difficult personal situation?",
    "How can I manage my time when dealing with a difficult health issue?",
    "How can I manage my time when dealing with a difficult personal situation?",
    "How can I manage my time when dealing with a difficult health issue?",
    "How can I manage my time when dealing with a difficult financial situation?",
    "How can I manage my time when dealing with a difficult emotional situation?",
    "How can I manage my time when dealing with a difficult mental health issue?",
    "How can I manage my time when dealing with a difficult relationship?",
    "How can I manage my time when dealing with a difficult addiction?",
    "How can I manage my time when dealing with a difficult life transition?",
  ];
  final selfImprovement = [
    "What is self-improvement, and why is it important?",
    "What are some effective self-improvement strategies?",
    "How can you develop good habits and break bad ones?",
    "How can you improve your time management skills?",
    "How can you increase your productivity and efficiency?",
    "What are some tips for improving your focus and concentration?",
    "How can you improve your communication skills?",
    "How can you improve your emotional intelligence?",
    "What are some effective stress-management techniques?",
    "How can you improve your confidence and self-esteem?",
    "How can you develop a growth mindset?",
    "How can you overcome procrastination?",
    "How can you improve your creativity?",
    "What are some effective goal-setting strategies?",
    "How can you improve your decision- making skills?",
    "How can you improve your problem- solving skills?",
    "What are some effective mindfulness techniques?",
    "How can you improve your memory and retention skills?",
    "How can you improve your public speaking skills?",
    "How can you develop better relationships with others?",
    "How can you improve your listening skills?",
    "How can you develop your leadership skills?",
    "How can you become more assertive?",
    "What are some effective networking strategies?",
    "How can you improve your conflict resolution skills?",
    "How can you improve your negotiation skills?",
    "How can you develop better self-care habits?",
    "How can you improve your financial management skills?",
    "How can you improve your fitness and health?",
    "How can you improve your sleep habits?",
    "How can you improve your time management when it comes to social media and technology?",
    "How can you improve your professional skills for your career?",
    "How can you develop your emotional regulation skills?",
    "What are some effective communication skills for working in a team?",
    "How can you improve your ability to adapt to change?",
    "How can you become a more effective problem solver?",
    "How can you become a more effective decision-maker?",
    "How can you develop better conflict resolution skills?",
    "How can you improve your stress- management techniques in a work environment?",
    "How can you develop better work-life balance?",
    "How can you improve your self-reflection skills?",
    "How can you develop better learning habits?",
    "How can you improve your listening skills in order to better understand others?",
    "How can you develop better self-awareness?",
    "How can you improve your ability to provide constructive feedback?",
    "How can you improve your networking skills in order to develop better connections?",
    "How can you improve your critical thinking skills?",
    "How can you improve your ability to handle criticism?",
    "How can you develop better organisational skills?",
    "How can you improve your ability to maintain motivation towards your goals?",
  ];
  final investmentAndTrading = [
    "What is investment?",
    "What is trading?",
    "What is the difference between investing and trading?",
    "How do you create an investment portfolio?",
    "What are the different types of investment portfolios?",
    "How do you measure the success of an investment portfolio?",
    "What is diversification in investing?",
    "How do you diversify your investment portfolio?",
    "What are the benefits of diversification in investing?",
    "What is a stock?",
    "How do you buy and sell stocks?",
    "What is the stock market?",
    "How does the stock market work?",
    "What are the different types of stocks?",
    "How do you analyse stocks?",
    "What is a mutual fund?",
    "How does a mutual fund work?",
    "What are the benefits of investing in mutual funds?",
    "What is an exchange-traded fund (ETF)?",
    "How does an ETF work?",
    "What are the benefits of investing in ETFs?",
    "What is a bond?",
    "How do bonds work?",
    "What are the benefits of investing in bonds?",
    "What is a certificate of deposit (CD)?",
    "How does a CD work?",
    "What are the benefits of investing in CDs?",
    "What is a money market account?",
    "How does a money market account work?",
    "What are the benefits of investing in a money market account?",
    "What is an annuity?",
    "How does an annuity work?",
    "What is a retirement account?",
    "How do retirement accounts work?",
    "What are the benefits of investing in a retirement account?",
    "What is a 401(k)?",
    "How does a 401(k) work?",
    "What are the benefits of investing in a 401(k)?",
    "What is a Roth IRA?",
    "How does a Roth IRA work?",
    "What are the benefits of investing in a Roth IRA?",
    "What is a traditional IRA?",
    "How does a traditional IRA work?",
    "What are the benefits of investing in a traditional IRA?",
    "What is day trading?",
    "How does day trading work?",
    "What are the risks of day trading?",
    "What is swing trading?",
    "How does swing trading work?",
  ];
  final mentalHealth = [
    "What are the signs of depression?",
    "How can I manage anxiety?",
    "How do I cope with stress?",
    "What is bipolar disorder?",
    "How can I manage my anger?",
    "How can I improve my self-esteem?",
    "How do I deal with social anxiety?",
    "What are the symptoms of PTSD?",
    "How can I manage my OCD?",
    "How do I cope with grief and loss?",
    "What is borderline personality disorder?",
    "How can I manage my panic attacks?",
    "How do I know if I have ADHD?",
    "What are the signs of narcissistic personality disorder?",
    "How can I improve my sleep habits?",
    "How do I cope with a traumatic experience?",
    "What are the symptoms of schizophrenia?",
    "How can I manage my phobias?",
    "What are the signs of postpartum depression?",
    "How can I improve my memory?",
    "How do I cope with a chronic illness?",
    "What are the signs of an eating disorder?",
    "How can I manage my addictions?",
    "What is seasonal affective disorder?",
    "How can I improve my emotional intelligence?",
    "How do I cope with body dysmorphia?",
    "What are the symptoms of dissociative identity disorder?",
    "How can I manage my stress-related physical symptoms?",
    "What is generalised anxiety disorder?",
    "How can I improve my time management skills?",
    "How do I cope with a breakup or divorce?",
    "What are the signs of a panic disorder?",
    "How can I manage my paranoia?",
    "What is post-traumatic stress disorder?",
    "How can I improve my focus and concentration?",
    "How do I cope with a job loss or unemployment?",
    "What are the symptoms of agoraphobia?",
    "How can I manage my mood swings?",
    "What is obsessive-compulsive disorder?",
    "How can I improve my resilience?",
    "How do I cope with a toxic relationship?",
    "What are the signs of borderline",
    "personality disorder?",
    "How can I manage my suicidal thoughts?",
    "What is social anxiety disorder?",
    "How can I improve my resilience?",
    "How do I cope with a toxic relationship?",
    "What are the signs of borderline personality disorder?",
    "How can I manage my suicidal thoughts?",
    "What is social anxiety disorder?",
    "How can I improve my coping skills?",
    "How do I cope with chronic pain?",
    "What are the symptoms of a personality disorder?",
    "How can I manage my self-harm urges?",
    "What is a psychotic disorder?",
    "How can I improve my mental health overall?",
  ];
  final healthConditionsAndDiseases = [
    "What is a health condition?",
    "What is a disease?",
    "What is the difference between a health condition and a disease?",
    "What are the most common health conditions?",
    "What are the most common diseases? >",
    "What is diabetes?",
    "What causes diabetes?",
    "What are the symptoms of diabetes?",
    "How is diabetes treated?",
    "What is heart disease?",
    "What causes heart disease?",
    "What are the symptoms of heart disease?",
    "How is heart disease treated?",
    "What is cancer?",
    "What causes cancer?",
    "What are the symptoms of cancer?",
    "How is cancer treated?",
    "What is Alzheimer's disease?",
    "What causes Alzheimer's disease?",
    "What are the symptoms of Alzheimer's disease?",
    "How is Alzheimer's disease treated?",
    "What is arthritis?",
    "What causes arthritis?",
    "What are the symptoms of arthritis?",
    "How is arthritis treated?",
    "What is asthma?",
    "What causes asthma?",
    "What are the symptoms of asthma?",
    "How is asthma treated?",
    "What is chronic obstructive pulmonary",
    "disease (COPD)?",
    "What causes COPD?",
    "What are the symptoms of COPD?",
    "How is COPD treated?",
    "What is depression?",
    "What causes depression?",
    "What are the symptoms of depression?",
    "How is depression treated?",
    "What is anxiety?",
    "What causes anxiety?",
    "What are the symptoms of anxiety?",
    "How is anxiety treated?",
    "What is obesity?",
    "What causes obesity?",
    "What are the symptoms of obesity?",
    "How is obesity treated?",
    "What is hypertension (high blood pressure)?",
    "What causes hypertension?",
    "What are the symptoms of hypertension?",
    "How is hypertension treated?",
    "What is HIV/AIDS?",
    "What causes HIV/AIDS?",
    "What are the symptoms of HIV/AIDS?",
    "How is HIV/AIDS treated?",
    "What is the difference between a virus and a bacterial infection?",
    "How can you prevent the spread of infectious diseases?",
  ];
  final nutritionAndDiet = [
    "What is a balanced diet and why is it important?",
    "How can one determine their daily caloric needs?",
    "What are the basic macronutrients (carbohydrates, proteins, and fats) and how much of each should be consumed?",
    "What are the basic micronutrients (vitamins and minerals) and what are their functions?",
    "What are some common myths about nutrition and diet?",
    "What is the relationship between nutrition and weight management?",
    "How can one make healthier food choices when eating out?",
    "What are some strategies for meal planning and preparation?",
    "What is the role of hydration in nutrition?",
    "How can one incorporate more fruits and vegetables into their diet?",
    "What is the impact of processed foods on health?",
    "How can one reduce their intake of added sugars and sweeteners?",
    "What are some common deficiencies in the modern diet and how can they be addressed?",
    "What is the impact of alcohol consumption on health?",
    "How can one read and interpret nutrition labels?",
    "What are some strategies for controlling portion sizes?",
    "What is the role of dietary supplements?",
    "How can one balance their diet when following a specific dietary restriction (e.g. vegetarian, vegan, gluten-free)?",
    "What is the relationship between nutrition and mental health?",
    "What is the impact of caffeine consumption on health?",
    "How can one reduce their intake of saturated and trans fats?",
    "What are some common dietary strategies for managing chronic conditions (e.g. diabetes, high blood pressure, heart disease)?",
    "What is the role of fiber in nutrition?",
    "How can one manage cravings and temptations when trying to maintain a healthy diet?",
  ];
  final travel = [
    "What are some budget-friendly travel options?",
    "How do I plan a trip around my interests?",
    "What are the best ways to find travel deals?",
    "How do I choose the best travel credit card?",
    "What are some travel safety tips?",
    "How do I choose the best travel insurance?",
    "What are the best travel apps to use?",
    "How do I pack efficiently for a trip?",
    "What are the best ways to travel sustainably?",
    "What are some unique travel experiences I can have?",
    "How do I make the most of a short trip?",
    "How do I overcome travel anxiety?",
    "What are some solo travel tips?",
    "What are some family-friendly travel options?",
    "What are some romantic travel destinations?",
    "What are some adventure travel options?",
    "What are some cultural travel experiences I can have?",
    "What are some foodie travel destinations?",
    "What are some underrated travel destinations?",
    "How do I plan a backpacking trip?",
    "What are some photogenic travel destinations?",
    "How do I avoid tourist traps while traveling?",
    "How do I travel sustainably?",
    "What are some luxury travel options?",
    "What are some unique accommodations I can stay in?",
    "How do I find the best local experiences? >",
    "What are some travel photography tips? >",
    "What are some travel gadgets to bring on a trip?",
    "How do I stay connected while traveling abroad?",
    "How do I navigate public transportation in a foreign country?",
  ];
  final foodAndCooking = [
    "What are some basic cooking technique for beginners?",
    "What are some easy and healthy meal ideas?",
    "How can you cook with limited ingredients or equipment?",
    "What are some tips for meal planning and grocery shopping?",
    "How can you cook on a budget?",
    "What are some common kitchen mistakes and how to avoid them?",
    "What are some popular international cuisines to try?",
    "What are some common kitchen tools and their uses?",
    "What are some common cooking terms and definitions?",
    "What are some healthy alternatives for common ingredients?",
    "How can you make homemade sauces and condiments?",
    "What are some common kitchen substitutions?",
    "How can you cook for a large group of people?",
    "How can you cook for people with dietary restrictions?",
    "What are some tips for cooking with children?",
    "What are some popular cooking techniques, such as grilling or baking?",
    "How can you cook for a special occasion or holiday?",
    "What are some common meal prep strategies?",
    "What are some healthy breakfast options?",
    "What are some healthy snacks for on- the-go?",
    "What are some vegetarian or vegan meal ideas?",
    "What are some tips for baking desserts?",
    "How can you make homemade bread or pizza dough?",
    "What are some tips for cooking with seafood?",
    "What are some popular types of meat and how to cook them?",
    "How can you cook for a romantic dinner?",
  ];
  final healthAndWellness = [
    "How can I improve my overall health and well-being?",
    "What are the most effective ways to lose weight and maintain a healthy weight?",
    "How can I improve my diet and nutrition?",
    "What are the best ways to manage stress and anxiety?",
    "How can I improve my sleep habits and overcome insomnia?",
    "What are the most effective exercises for improving fitness and endurance?",
    "How can I develop a workout routine that meets my needs?",
    "What are the best ways to stay motivated and committed to a fitness regimen?",
    "What are the best ways to prevent and manage chronic diseases like diabetes or heart disease?",
    "What are the most effective ways to manage pain and discomfort?",
    "What are the best ways to manage mental health conditions like depression or anxiety?",
    "How can I improve my mindfulness and meditation practices?",
    "What are the best ways to improve my self-care routine?",
    "What are the most effective ways to manage allergies and other common health conditions?",
    "How can I improve my immune system and prevent illness?",
    "What are the best ways to manage chronic pain?",
    "How can I improve my posture and prevent back pain?",
    "What are the best ways to manage menstrual cramps and other women's health issues?",
    "How can I improve my digestion and gut health?",
    "What are the best ways to manage skin conditions like acne or eczema?",
    "How can I manage my allergies and avoid triggers?",
    "What are the best ways to manage migraines and other headaches?",
    "How can I improve my dental health and prevent cavities and gum disease?",
  ];
  final sportsAndFitness = [
    "What are the benefits of exercising regularly?",
    "What are the best exercises for building strength?",
    "What are the best exercises for improving flexibility?",
    "How often should I work out to stay healthy?",
    "What are some good exercises for weight loss?",
    "What are the most effective workouts for gaining muscle mass?",
    "How can I improve my endurance for sports and fitness?",
    "What are some tips for staying motivated to exercise?",
    "What are some good ways to warm up before exercising?",
    "What are some good stretches to do after exercising?",
    "What is the best time of day to work out?",
    "What should I eat before and after exercising?",
    "How can I prevent injuries while exercising?",
    "What are some common mistakes people make when exercising?",
    "What is the difference between cardio and strength training?",
    "How much cardio should I do each week?",
    "How much strength training should I do each week?",
    "What are some good exercises for improving balance?",
    "How can I improve my posture?",
    "What is the best way to track progress in fitness?",
    "What are the most important muscles to exercise?",
    "How can I get better at a specific sport?",
    "What are some good exercises for runners?",
    "What are some good exercises for swimmers?",
    "What are some good exercises for cyclists?",
    "What are some good exercises for golfers?",
  ];
  final fitnessAndExercise = [
    "What are the benefits of exercise?",
    "What are the different types of exercise?",
    "How often should you exercise?",
    "What is cardio?",
    "What are the benefits of cardio?",
    "What are some examples of cardio exercises?",
    "What is strength training?",
    "What are the benefits of strength training?",
    "What are some examples of strength training exercises?",
    "What is flexibility?",
    "What are the benefits of flexibility?",
    "What are some examples of flexibility exercises?",
    "How do you warm up before exercising? >",
    "How do you cool down after exercising? >",
    "What are the best exercises for weight loss?",
    "How can you increase your endurance?",
    "What are the best exercises for building muscle?",
    "What are the best exercises for toning?",
    "What are the best exercises for improving posture?",
    "What are the best exercises for improving balance?",
    "What is a personal trainer?",
    "What services do personal trainers provide?",
    "How do you find a good personal trainer?",
    "What is a fitness coach?",
    "What services do fitness coaches provide?",
    "How do you find a good fitness coach?",
    "What is a workout plan?",
    "How do you create a workout plan?",
    "What is a rest day?",
    "How often should you take a rest day?",
    "What is a healthy diet?",
    "What are the best foods to eat before exercising?",
  ];
  final relationships = [
    "How can I improve my communication with my partner?",
    "How do I know if my partner is right for me?",
    "What are the signs of a healthy relationship?",
    "How do I deal with conflicts in a relationship?",
    "What are some common relationship problems and how do I fix them?",
    "How do I know if I am ready for a committed relationship?",
    "How can I build trust in a relationship?",
    "What are some tips for maintaining a long-distance relationship?",
    "How can I cope with a breakup?",
    "How can I deal with a partner who has different political views than me?",
    "How can I handle a partner who is going through a tough time?",
    "How do I deal with a partner who has addiction issues?",
    "What are some healthy boundaries to set in a relationship?",
    "How can I deal with my partner's family?",
    "How do I know if my relationship is toxic?",
    "How can I improve my sex life with my partner?",
    "How do I deal with a partner who is emotionally distant?",
    "How do I know if my partner is emotionally abusive?",
    "How do I deal with jealousy in a relationship?",
    "How can I balance my relationship with other aspects of my life, such as work or friends?",
    "How can I deal with a partner who has a different religion or culture than me?",
    "How do I know when it's time to move on from a relationship?",
    "What are some tips for starting a new relationship?",
    "How can I get over my ex?",
    "How do I know if my partner is cheating on me?",
    "How can I improve intimacy in my relationship?",
  ];
  final agingAndSeniorCare = [
    "What is aging and what are its effects on the body?",
    "What are some common health concerns for seniors?",
    "What are some tips for healthy aging?",
    "How can seniors stay physically active and mobile?",
    "How can seniors maintain mental agility and prevent cognitive decline?",
    "How can seniors stay socially connected and engaged?",
    "What are some common financial concerns for seniors?",
    "What are some options for housing and living arrangements for seniors?",
    "What are some common challenges of caring for an aging loved one?",
    "What are some resources available for caregivers of seniors?",
    "What are some options for long-term care for seniors?",
    "What are some ways to ensure medication management for seniors?",
    "What are some strategies for fall prevention for seniors?",
    "How can seniors manage chronic pain?",
    "How can seniors cope with the loss of loved ones?",
    "What are some ways to address end-of- life planning for seniors?",
    "What are some common age-related vision changes and how can they be managed?",
    "What are some ways to ensure proper nutrition for seniors?",
    "How can seniors maintain a healthy sleep schedule?",
    "What are some tips for preventing loneliness and isolation in seniors?",
    "What are some ways to address incontinence issues in seniors?",
    "What are some common dental issues that seniors face and how can they be managed?",
    "What are some ways to maintain emotional and mental well-being in seniors?",
    "What are some common skin changes that occur with age and how can they b managed?",
  ];
  final shoppingAndConsumerAdvice = [
    "What are some strategies for finding the best deals while shopping?",
    "How do I avoid scams and fraudulent websites while shopping online?",
    "What are some tips for creating a budget-friendly shopping list?",
    "How do I choose the right size when shopping for clothing online?",
    "What are some common mistakes to avoid when shopping for groceries?",
    "How do I determine if a product is worth the price?",
    "How do I research and compare prices of products before making a purchase?",
    "What are some tips for saving money on everyday household items?",
    "How can I be a more eco-friendly consumer?",
    "How do I avoid impulse purchases while shopping?",
    "What are some strategies for finding unique and unusual products while shopping?",
    "How do I choose the right product when there are many options available?",
    "What are some tips for finding quality products at affordable prices?",
    "How do I handle returns and refunds when shopping online?",
    "What are some strategies for finding the best deals during holiday sales?",
    "How do I choose the right shoes for my feet and lifestyle?",
    "What are some tips for finding the best deals on travel and vacation packages?",
    "How do I find products that are cruelty-free and not tested on animals?",
    "What are some strategies for finding the best deals on home appliances?",
    "How do I choose the right skincare products for my skin type?",
    "What are some tips for finding the best deals on furniture?",
    "How do I avoid impulse purchases when shopping in-person?",
  ];
  final petsAndAnimals = [
    "What are the most popular types of pets?",
    "What are the best pets for apartments or small spaces?",
    "How do I choose the right pet for me?",
    "How do I prepare my home for a new pet?",
    "What are the best ways to bond with my pet?",
    "How do I train my pet?",
    "How do I potty train my pet?",
    "What are the best ways to discipline my pet?",
    "How do I groom my pet?",
    "What are the best foods to feed my pet?",
    "How often should I feed my pet?",
    "What are the best treats for my pet?",
    "How much exercise does my pet need?",
    "What are the best types of exercise for my pet?",
    "How do I keep my pet healthy?",
    "What are the most common health problems in pets?",
    "How often should I take my pet to the vet?",
    "What vaccinations does my pet need?",
    "What are the best ways to prevent fleas and ticks on my pet?",
    "How do I handle a pet emergency?",
    "How do I handle pet anxiety?",
    "How do I introduce my pet to other pets?",
    "What are the best ways to travel with my pet?",
    "How do I keep my pet safe in the car?",
    "How do I find a pet-friendly hotel?",
    "How do I prepare my pet for a move?",
    "How do I handle pet allergies?",
    "What are the best ways to keep my pet entertained?",
    "How do I teach my pet new tricks?",
    "How do I handle pet aggression?",
    "How do I handle pet separation anxiety?",
    "How do I handle pet behavior problems?",
  ];
  final parentingAndFamily = [
    "What is parenting?",
    "What are the qualities of a good parent?",
    "What are the most important parenting skills?",
    "What is a family?",
    "What are the benefits of a strong family unit?",
    "What are the most common types of families?",
    "What is a nuclear family?",
    "What is an extended family?",
    "What is a blended family?",
    "How do I foster positive relationships within my family?",
    "What is discipline?",
    "How do I homeschool my child effectively?",
    "What is child psychology?",
    "How do I understand my child's behavior?",
    "What is effective communication in parenting?",
    "How do I communicate with my child effectively?",
    "What is the role of technology in parenting?",
    "How do I manage screen time for my child?",
    "What is the role of nutrition in parenting? >",
    "How do I ensure my child gets a healthy diet?",
    "How do I discipline my children effectively?",
    "What is positive parenting?",
    "How do I practice positive parenting?",
    "What is attachment parenting?",
    "How do I practice attachment parenting?",
    "What is child development?",
    "What are the different stages of child development?",
    "What is the role of education in parenting?",
    "How do I choose the right school for my child?",
    "What is homeschooling?",
  ];
  final philosophy = [
    "What is philosophy?",
    "What are the different branches of philosophy?",
    "What is the difference between Eastern and Western philosophy?",
    "What is the meaning of life according to philosophy?",
    "What is the nature of reality according to philosophy?",
    "What is the role of ethics in philosophy?",
    "What is the relationship between philosophy and science?",
    "What is the concept of free will in philosophy?",
    "What is the role of reason in philosophy?",
    "What are some famous philosophers and their teachings?",
    "What is the philosophy of mind?",
    "What is the philosophy of religion?",
    "What is the philosophy of art?",
    "What is the philosophy of language?",
    "What is the philosophy of education?",
    "What is the philosophy of history?",
    "What is the philosophy of politics?",
    "What is the philosophy of law?",
    "What is the philosophy of economics?",
    "What is the philosophy of mathematics?",
    "What is the philosophy of science?",
    "What is the philosophy of technology?",
    "What is the philosophy of medicine?",
    "What is the philosophy of psychology?",
    "What is the philosophy of love?",
    "What is the philosophy of beauty?",
    "What is the philosophy of happiness?",
    "What is the philosophy of humor?",
    "What is the philosophy of death?",
    "What is the philosophy of time?",
    "What is the philosophy of space?",
    "What is the philosophy of identity?",
    "What is the philosophy of knowledge?",
    "What is the philosophy of truth?",
    "What is the philosophy of reality?",
  ];
  final spiritualityAndReligion = [
    "What is spirituality and how is it different from religion?",
    "What are some common beliefs and practices in major world religions?",
    "How can one find their own spiritual path?",
    "What is the role of prayer and meditation in spirituality and religion?",
    "How can one cultivate a deeper sense of spiritual connection?",
    "What are some ways to live a more mindful and intentional life?",
    "How can one reconcile their spirituality with scientific knowledge?",
    "What are some common misconceptions about spirituality and religion?",
    "What is the role of community in spirituality and religion?",
    "How can one find meaning and purpose in life through spirituality?",
    "What are some ways to cope with grief and loss through spirituality?",
    "How can one develop a more compassionate and empathetic outlook through spirituality?",
    "What is the role of forgiveness in spirituality and religion?",
    "What are some ways to cultivate a sense of gratitude through spirituality?",
    "What is the role of faith in spirituality and religion?",
    "What are some ways to deal with doubt and uncertainty in spirituality and religion?",
    "How can one find a sense of inner peace through spirituality?",
    "What is the role of love and compassion in spirituality and religion?",
    "What is the role of service and altruism in spirituality and religion?",
    "How can one connect with nature and the natural world through spirituality?",
    "What is the role of ritual and ceremony in spirituality and religion?",
    "What are some ways to address religious and spiritual intolerance?",
    "How can one find spiritual guidance and support?",
    "What are some ways to live in harmony with others of different spiritual beliefs?",
    "What is the role of silence and solitude spirituality and religion?",
  ];
  final humanBehaviourAndPsychology = [
    "What is human behaviour?",
    "What is psychology?",
    "What is the difference between human behaviour and psychology?",
    "What are the most common theories of human behaviour?",
    "What are the most common theories of psychology?",
    "What is the nature vs. nurture debate?",
    "How does culture influence human behaviour?",
    "What is social psychology?",
    "What are the most common social psychology theories?",
    "What is cognitive psychology?",
    "What are the most common cognitive psychology theories?",
    "What is behavioural psychology?",
    "What are the most common behavioural psychology theories?",
    "What is developmental psychology?",
    "What are the most common developmental psychology theories?",
    "What is abnormal psychology?",
    "What are the most common abnormal psychology theories?",
    "What is positive psychology?",
    "What are the most common positive psychology theories?",
    "What are the most common psychological disorders?",
    "What are the symptoms of anxiety?",
    "What are the symptoms of depression? >",
    "What are the symptoms of bipolar disorder?",
    "What are the symptoms of schizophrenia?",
    "How are psychological disorders diagnosed?",
    "What is psychotherapy?",
    "What are the most common types of psychotherapy?",
    "What is cognitive-behavioural therapy (CBT)?",
    "How does CBT work?",
    "What is psychoanalysis?",
  ];
  List questionList = List.empty().obs;

  @override
  void onInit() {
    questionList = [
      ///Self Growth
      {
        "title": "Self Growth",
        "subQuestion": [
          {
            "subTitle": "Personal Finance",
            "question": personalFinance,
          },
          {
            "subTitle": "Personal Development",
            "question": personalDevelopment,
          },
          {
            "subTitle": "Time management and productivity",
            "question": timeManagementAndProductivity,
          },
          {
            "subTitle": "Self-improvement",
            "question": selfImprovement,
          },
          {
            "subTitle": "Investment anf trading",
            "question": investmentAndTrading,
          },
        ],
      },

      ///Self Care
      {
        "title": "Self Care",
        "subQuestion": [
          {
            "subTitle": "Mental health",
            "question": mentalHealth,
          },
          {
            "subTitle": "Health conditions and diseases",
            "question": healthConditionsAndDiseases,
          },
          {
            "subTitle": "Nutrition diet",
            "question": nutritionAndDiet,
          },
          {
            "subTitle": "Travel",
            "question": travel,
          },
          {
            "subTitle": "Food and cooking",
            "question": foodAndCooking,
          },
        ],
      },

      ///health
      {
        "title": "Health",
        "subQuestion": [
          {
            "subTitle": "Health and wellness",
            "question": healthAndWellness,
          },
          {
            "subTitle": "Sports and fitness",
            "question": sportsAndFitness,
          },
          {
            "subTitle": "Fitness and exercise",
            "question": fitnessAndExercise,
          },
        ],
      },

      ///love
      {
        "title": "Love",
        "subQuestion": [
          {
            "subTitle": "Relationships",
            "question": relationships,
          },
        ],
      },

      ///Family
      {
        "title": "Family",
        "subQuestion": [
          {
            "subTitle": "Aging and seniorCare",
            "question": agingAndSeniorCare,
          },
          {
            "subTitle": "Shopping and consumer advice",
            "question": shoppingAndConsumerAdvice,
          },
          {
            "subTitle": "Pets and animals",
            "question": petsAndAnimals,
          },
          {
            "subTitle": "Parenting and family",
            "question": parentingAndFamily,
          },
        ],
      },

      ///Philosophy
      {
        "title": "Philosophy",
        "subQuestion": [
          {
            "subTitle": "Philosophy",
            "question": philosophy,
          },
          {
            "subTitle": "Spirituality and religion",
            "question": spiritualityAndReligion,
          },
          {
            "subTitle": "Human behaviour and psychology",
            "question": humanBehaviourAndPsychology,
          },
        ],
      },

      ///Education
      {
        "title": "Education",
        "subQuestion": [
          {
            "subTitle": "Relationships",
            "question": selfImprovement,
          },
        ],
      },

      ///Plant
      {
        "title": "Plant",
        "subQuestion": [
          {
            "subTitle": "Relationships",
            "question": selfImprovement,
          },
        ],
      },

      ///Job
      {
        "title": "Job",
        "subQuestion": [
          {
            "subTitle": "Relationships Job",
            "question": selfImprovement,
          },
        ],
      },

      ///Entertainment
      {
        "title": "Entertainment",
        "subQuestion": [
          {
            "subTitle": "Relationships",
            "question": selfImprovement,
          },
        ],
      },

      ///Social
      {
        "title": "Social",
        "subQuestion": [
          {
            "subTitle": "Relationships",
            "question": selfImprovement,
          },
        ],
      },

      ///Business
      {
        "title": "Business",
        "subQuestion": [
          {
            "subTitle": "Relationships",
            "question": selfImprovement,
          },
        ],
      },

      ///Fashion
      {
        "title": "Business",
        "subQuestion": [
          {
            "subTitle": "Fashion",
            "question": selfImprovement,
          },
        ],
      },

      ///Others
      {
        "title": "Others",
        "subQuestion": [
          {
            "subTitle": "Relationships",
            "question": selfImprovement,
          },
        ],
      },
    ];

    super.onInit();
  }

  Future<void> readTextFromImage({required ImageSource imageSource, required String navigateBy}) async {
    FocusManager.instance.primaryFocus?.unfocus();
    var image = await ImagePicker().pickImage(source: imageSource);
    if (image != null) {
      await ImageCropper().cropImage(
        sourcePath: image.path,
        aspectRatioPresets: [
          CropAspectRatioPreset.square,
          CropAspectRatioPreset.ratio3x2,
          CropAspectRatioPreset.original,
          CropAspectRatioPreset.ratio4x3,
          CropAspectRatioPreset.ratio16x9
        ],
        uiSettings: [
          AndroidUiSettings(
              toolbarTitle: 'Crop Image',
              toolbarColor: AppColors.blackColor,
              toolbarWidgetColor: AppColors.whiteColor,
              initAspectRatio: CropAspectRatioPreset.original,
              lockAspectRatio: false,
              backgroundColor: AppColors.whiteColor.withOpacity(0.1),
              cropFrameColor: AppColors.primaryColor,
              activeControlsWidgetColor: AppColors.primaryColor,
              hideBottomControls: true),
          IOSUiSettings(
            title: 'Cropper',
          ),
        ],
      ).then((v) async {
        if (v != null) {
          showLoadingDialog();
          final inputImage = InputImage.fromFilePath(v.path);
          final textRecognizer = TextRecognizer(script: TextRecognitionScript.latin);
          final RecognizedText recognizedText = await textRecognizer.processImage(inputImage);
          String text = recognizedText.text;

          textRecognizer.close();
          if (navigateBy == "home") {
            messageCtr.value.text = text;
            messageCtr.refresh();
          } else if (navigateBy == "question") {
            commonQuestionCtr.value.text = text;
            commonQuestionCtr.refresh();
          } else if (navigateBy == "chat") {
            chatController.textController.value.text = text;
            chatController.textController.refresh();
          }
          hideLoadingDialog();
        }
      });
    }
  }
}
